




.build/pro328/src/LSM9DS1_Basic_SPI.cpp : src/LSM9DS1_Basic_SPI.ino
	@mkdir -p .build/pro328/src
	@echo [93msrc/LSM9DS1_Basic_SPI.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/pro328/src/LSM9DS1_Basic_SPI.cpp
	@true

